name: run-test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:

  start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start test"

  tests:
    needs: [ start ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [ "lint" , "prettier:check", "test" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: cd ./package && yarn && yarn install

      - name: Build
        run: cd ./package && yarn run ${{ matrix.test }}
